In [ ]:
import numpy as np
rand_matrix = np.random.randn(4,4)
rand_matrix
eig,_ = np.linalg.eig(rand_matrix)

In [10]:
rand_matrix

array([[ 1.34974657, -0.86074209, -0.82696852, -0.52129217],
       [ 1.61034993,  1.28649412, -0.37937537, -0.46502091],
       [ 1.15420626, -0.14489514, -0.21557423, -0.44293793],
       [ 0.45784596,  0.78548138,  1.16470277,  0.39705886]])

In [11]:
eig

array([0.95120906+1.64482556j, 0.95120906-1.64482556j,
       0.29558974+0.j        , 0.61971747+0.j        ])

一个随机矩阵的 特征值是复数的
但是一个实对称矩阵 可以分解为实特镇向量和实特征值   

In [ ]:
rand_matrix = np.triu(rand_matrix)
rand_matrix += rand_matrix.T - np.diag(rand_matrix.diagonal())
symmetric_matrix = rand_matrix
eig,_ = np.linalg.eig(symmetric_matrix)

In [20]:
eig

array([-1.18875768,  2.23411832,  1.21150543,  0.56085926])

正定矩阵 一定是对称矩阵 但是对成矩阵不一定是正定的， 判断对称矩阵是否正定：
- 所有特征值为正
- 所有顺序主子式为正
- 主元为正 则矩阵正定

AX = b 有不同的迭代解法   
共轭梯度的求解   
https://en.wikipedia.org/wiki/Conjugate_gradient_method


In [ ]:
rand_matrix = np.random.randn(5,5)
rand_matrix = np.triu(rand_matrix)
rand_matrix += rand_matrix.T - np.diag(rand_matrix.diagonal())
symmetric_matrix = rand_matrix
A = symmetric_matrix
b = np.random.randn(5)

In [40]:
from scipy.sparse import linalg as s_linalg

In [41]:
f,inf = s_linalg.minres(A,b)